### ISSUE TITLE
define how endpoints are found

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.mCSD#1]
Use-case - I want to use a mCSD directory to enable finding XCA/XDS endpoint details. Given I have a homeCommunityID, When I need to connect to the SOAP endpoint, Then I lookup the homeCommunityId in the directory and get the Endpoint details I need to connect. 
Thus need a profile on how homeCommunityId fits in mCSD, and how Endpoint holds XD* endpoint types.

**Comment by JohnMoehrke** [comment]
@jlamy I think CQ needs this, and has a solution. Right?

**Comment by jlamy** [comment]
If we treat this issue as an epic, the following issues are part of it:
- https://github.com/IHE/ITI.mCSD/issues/13
- https://github.com/IHE/ITI.mCSD/issues/2
- https://github.com/IHE/ITI.mCSD/issues/14
