### ISSUE TITLE
Define how to use IHE codes for Endpoint.connectionType

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.mCSD#14]
We need to describe, with examples, how various systems implementing IHE profiles would be represented in an mCSD directory using the IHE codes we are defining in https://github.com/IHE/ITI.mCSD/issues/13.

**Comment by jlamy** [comment]
Need to support these cases:
- XCA responding gateway with one endpoint
- XCA responding gateway with two endpoints: one for query, one for retrieve.

ITI has tentatively decided this:
- Short term (because Endpoint.connectionType is 1..1): use two Endpoints for both cases. In first case both will have the same URL.
- Long term: try to get Endpoint.connectionType to support >1. Then first case can be represented by one Endpoint with two codes.

**Comment by jlamy** [comment]
Another tentative decision: even if Endpoint.connectionType eventually supports >1, don't use the HL7 codes as well.

- Anyone who needs to interoperate needs the IHE codes
- Anyone who doesn't will not see a code they recognize (for example, to display to a user)

**Comment by lukeaduncan** [comment]
Included as part of MHD federation updates to mCSD.
