### ISSUE TITLE
ITI-90: prefixes on _lastUpdated search param

### ISSUE THREAD

**Issue by qligier** [IHE/ITI.mCSD#143]
**Section Number**
[2:3.90.4.1.2.1 Common Parameters](https://profiles.ihe.net/ITI/mCSD/ITI-90.html#23904121-common-parameters)

**Issue**
In ITI-90, the Care Services Selective Supplier shall support date prefixes on the `_lastUpdated` parameter:
> The Care Services Selective Supplier shall also support the following prefixes for the _lastUpdated parameter: gt, lt, ge, le, sa, and eb.

This will be an issue with systems that do mCSD/HPD conversion, as the DSML specification provides fewer filters for dates:

| Prefix | DSML |
|---|---|
| gt | No equivalent |
| lt | No equivalent |
| ge | `<dsml:greaterOrEqual />` |
| le | `<dsml:lessOrEqual />` |
| sa | No equivalent |
| eb | No equivalent |

**Proposed Change**
The requirement could be downgraded to a less strict 'should':
> The Care Services Selective Supplier **should** also support the following prefixes for the _lastUpdated parameter: gt, lt, ge, le, sa, and eb.

**Priority**:
- Medium?

**Comment by lukeaduncan** [comment]
Committee discussion doesn't find this persuasive.  There are use cases for the other prefixes and in a conversion you should be able to map those to the prefixes that are supported or filter the results before returning them.
