### ISSUE TITLE
Optionality of ITI-91 transaction

### ISSUE THREAD

**Issue by qligier** [IHE/ITI.mCSD#145]
**Section Number**
[1:46.1 mCSD Actors, Transactions, and Content Modules](https://profiles.ihe.net/ITI/mCSD/volume-1.html#1461-mcsd-actors-transactions-and-content-modules)

**Issue**
The mCSD requires supporting both the ITI-90 and ITI-91 transactions. This is quite unfortunate, because ITI-91 has a much narrower use-case. Querying the resources for discovery is much more common than duplicating the whole database, even more for mobile devices.
An implementer can't be compliant with mCSD if they only implement ITI-90, leading to either non-compliance or useless efforts in implementing the ITI-91 transaction.

**Proposed Change**
The ITI-91 transaction should be made optional.

**Priority**:
- High?

**Comment by lukeaduncan** [comment]
There are 2 different pairs of actors.  You only need to support the transaction for the actor you are implementing.  

Care Services **Selective** Consumer/Supplier require ITI-90.  
Care Services **Update** Consumer/Supplier require ITI-91.  

You only need to implement Care Services Selective Supplier if you only want to implement ITI-90.
