### ISSUE TITLE
Additional Context for Purpose-of-use extension

### ISSUE THREAD

**Issue by IrfanH99** [IHE/ITI.mCSD#156]
Section: In the IHE mCSD iGuide version 3.8.0, Endpoint Profile

Issue:  While doing validation of the Endpoint resource got the following message --  
"The extension https://profiles.ihe.net/ITI/mCSD/StructureDefinition/IHE.mCSD.PurposeOfUse is not allowed to be used at this point (allowed = e:MCSDOrganization, e:MCSDEndpoint; this element is [Endpoint])". 

Therefore, extension purpose-of-use can't be applied to the Endpoint resource as it's currently defined in mCSD. 

Proposed Change: The context of the extension needs to be updated to allow it to be added to resource of Endpoint and Organization to be properly used.

Priority: Medium

**Comment by lukeaduncan** [comment]
This was corrected in https://github.com/IHE/ITI.mCSD/pull/134.

At the next face to face we can review publishing this along with other corrections since then.

**Comment by IrfanH99** [comment]
We are publishing with the dependency to the in the package registry on mCSD 3.8.0. When do we anticipate the next package that has this issue addressed made available within the package registry instead of the CI build where it is present currently?

**Comment by lukeaduncan** [comment]
We'll review and vote on this during the next face to face meeting, Oct 21-25.  Then it goes through the publication process which will depend on demand and availability.

You can depend on the CI build until this can be re-published.
