### ISSUE TITLE
diagram source

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.mCSD#19]
many diagrams do not have editable source in the github repo

**Comment by lukeaduncan** [comment]
I added in the pptx files I had that were sources for the images.  I'm only seeing 2 images being used from these though, did you see any others I'm missing?  I will work on consolidating the pptx files when I have some more time so it's clear where it came from.

**Comment by citizenrich** [comment]
I don't think this is referring to the ones I made but if so I created bundle examples and uploaded them to ClinFHIR bundle visualizer which does the rendering. 

E.g. https://raw.githubusercontent.com/IHE/ITI.mCSD/main/input/images/coreonly.png

Another version required hand annotations on top of that render.
