### ISSUE TITLE
example codesystem needs to be clearly identified

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.mCSD#22]
http://profiles.ihe.net/ITI/mCSD/CodeSystem/mcsd-example-hierarchy

I think the current trend is to to have these marked as example codeSystems.

**Comment by lukeaduncan** [comment]
This has been updated and the QA is now happy.  The change involved making the URL use example.org for the CodeSystem.

https://github.com/IHE/ITI.mCSD/blob/main/input/fsh/example-mcsd.fsh#L36
