### ISSUE TITLE
OrganizationAffiliation for Document Sharing code profiling

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.mCSD#32]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

https://profiles.ihe.net/ITI/mCSD/3.6.1/StructureDefinition-IHE.mCSD.OrganizationAffiliation.DocShare.html

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Should the code be done as a slice or invariant?  or should the code bet limited to 1..1 (or 0..1).  Should code.coding be 1..1 instead of 1..*?

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by jlamy** [comment]
Needs research. Would like not to limit OrgAff.code to just our code.

**Comment by jlamy** [comment]
Where does "Required Pattern: At least the following" come from? It is in conflict with the requirement on all instances of .code.

We will probably have to use slicing to leave other codes unconstrained.

**Comment by jlamy** [comment]
Going with slicing.
