### ISSUE TITLE
mCSD_16: OrganizationAffiliation and mCSD Hierarchy Extension

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.mCSD#33]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*
I think we need to choose one option.  It seems confusing to have 2 different ways to accomplish the same thing.  It seems it would be better for interoperability to choose either OrganizationAffiliation or the extension, but not have both.

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.
High

**Comment by slagesse-epic** [comment]
I agree. I think that the document federation being profiled here is really just another hierarchy. I think it might make sense to use OrganizationAffiliation for all hierarchies since it is a standard FHIR Resource and seems to fit the same usage pattern as the mCSD extension.

**Comment by jlamy** [comment]
Would be easy to convert from extension to OrgAff for implementers in TI.
Would be extra work, maybe needing another PC period.

Plan: mock up as a pull request, leave open for discussion if needed.
