### ISSUE TITLE
1:46.8 mCSD Endpoint Usage Considerations

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.mCSD#37]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
[1:46.8 mCSD Endpoint Usage Considerations](https://profiles.ihe.net/ITI/mCSD/3.6.1/volume-1.html#1468-mcsd-endpoint-usage-considerations)

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*
This isn't really defining anything, but giving some options for various scenarios.  This may fit better in a white paper and even the mCSD white paper as it seems similar to content already there.  Or perhaps it needs to define a specific way to solve the issue if there is a single way that would work.  Responding to mCSD_10 open issue.

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*
Move to white paper?

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.
Medium

**Comment by jlamy** [comment]
Will leave open for the time being. Base outcome on relationship of normative Endpoint content to mCSD - whether we pull any out.
