### ISSUE TITLE
1:46.8.4 Endpoint Discovery Usage

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.mCSD#38]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
[1:46.8.4 Endpoint Discovery Usage](https://profiles.ihe.net/ITI/mCSD/3.6.1/volume-1.html#14684-endpoint-discovery-usage)

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Using MAY here doesn't seem very useful, and this solution looks very complicated to implement.  There is a lot of traversing of an unknown amount of resources to find a particular endpoint.  If more than one endpoint is found, how do you determine which is the correct one to use?  Is there any reason we don't dictate putting a reference to the Endpoint in the Organization that uses it directly?  Or perhaps in the OrganizationAffiliation itself if the endpoint is specific to the relationship?

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*
Define one way to perform endpoint lookups.

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.
Medium

**Comment by jlamy** [comment]
•	One example is...
•	Give a couple of examples

**Comment by jlamy** [comment]
Reworked the section.

**Comment by jlamy** [comment]
Committee: too specific for Vol 1. Moving to Vol 2 Appendix Y (existing CSD appendix), separate markdown file.
