### ISSUE TITLE
Endpoint Definition Clarification

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#39]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:46

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

"An Organization may be reachable through electronic Endpoint(s)." is slightly less specific than I think we should be. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

"An Organization may be reachable for electronic data exchange through electronic Endpoint(s)."

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by jlamy** [comment]
Agree
