### ISSUE TITLE
Multiple vs Single Endpoint Description Is Unclear

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#42]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:46.4.2.6.1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The following text implies that an organization can have a single endpoint for FHIR or multiple endpoints for XD* types of transactions. I think what it is trying to say is that some communication channels can be expressed by a single endpoint (FHIR) while others might require multiple endpoints (XCA, XCPD, etc.)

"Organizations may have a single endpoint for a technical mechanism like FHIR (e.g., a single Service Base URL), or multiple endpoints (e.g., IHE XCPD, IHE XCA Query Responding Gateway, IHE XCA Retrieve Responding Gateway, etc.)."

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

"Organizations may have one or more endpoints depending on the communication channels they support. For example, a server that only supports FHIR communication might have only a single endpoint, while a server that supports, for example, the IHE XCPD or XCA integration profiles would need to have multiple endpoints to support each transaction. Servers can support many communication channels, each of which might have one or more endpoints. 

"Organizations might support one or many communication channels, each of which might have one or more distinct endpoints. For example, a FHIR communication channel might require only a single endpoint, while an IHE XCA communication channel might require separate endpoints for each transaction"

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by jlamy** [comment]
Going with the second rec.

**Comment by jlamy** [comment]
Keep the e.g.
