### ISSUE TITLE
Do Not Require Servers Support Searches on Endpoint, Organization.endpoint, or OrganizationAffiliation.endpoint

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#51]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.90.4.1.2

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

It is not clear to me what the use case for searching on Organization.endpoint, OrganizationAffiliation.endpoint, or the Endpoint Resource itself is. Clients will generally first search for Organizations that they wish to communicate with and then move on to discovering the Endpoints for those Organizations. Thus, requiring servers to support searches for Endpoints will not bring much value but might have significant cost for servers that store Endpoints as part of the Organization data structure. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Remove the requirement to support searches on Organization.Endpoint, OrganizationAffiliation.Endpoint, or Endpoint itself. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by jlamy** [comment]
I'm inclined to agree. Let's discuss.

**Comment by jlamy** [comment]
2:3.90.4.1.2.8 Endpoint Resource Message Semantics: remove all but identifier.
2:3.90.4.1.2.9 OrganizationAffiliation Resource Message Semantics: remove endpoint.connection-type
endpoint.payload-type (same for Org)

**Comment by lukeaduncan** [comment]
Review full list during face to face to remove any not required by use cases.

Also address what combinations are required.
