### ISSUE TITLE
HTTP Responses Defined in Request Semantics

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#55]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.90.4.3.3

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

This section specifies the HTTP response code and body for the response to an ITI-90 request, but the next section also defines the response message. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Move the content from this section to section 2:3.90.4.4

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by lukeaduncan** [comment]
We do have this pattern in other places (e.g. PDQm https://profiles.ihe.net/ITI/PDQm/ITI-78.html#2378413-expected-actions).  This comment makes sense to me though.  We can discuss during the comment review call.  Any thoughts @lynnfel @JohnMoehrke ?
