### ISSUE TITLE
Define PurposeOfUse Extension on Endpoint and Organization

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#59]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

In existing deployments, there is a use to associate both Organization and Endpoint with a PurposeOfUse

Associating an Organization with a PurposeOfUse can be used to indicate the purposes for which the Organization can be expected to request data. 

Associating an Endpoint with a PurposeOfUse can be used to indicate the purposes for which that Endpoint is willing to respond to requests for data. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Define a PurposeOfUse CodeableConcept extension on both Organization and Endpoint. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by lukeaduncan** [comment]
Add purpose of use extension to Organization and Endpoint as 0..* CodeableConcept.
