### ISSUE TITLE
Relationship Between intendedRecipient and mCSD

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#60]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Open Issue mCSD_15

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

	
Profiling the relationship between intendedRecipient and values found in the mCSD directory is one of the most critical pieces missing for federated push messaging. However, I'm not sure if this belongs in the mCSD IG, the XDR integration profile, a whitepaper, or elsewhere.  

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by jlamy** [comment]
I agree. We don't want to repeat the work done to profile ITI-41 intendedRecipient = Direct address, but there needs to be a place where similar profiling lives, e.g. ITI-41 intendedRecipient = Organization connected via OrgAff with code DocShare-federate.

**Comment by lukeaduncan** [comment]
Copied content to #101
