### ISSUE TITLE
SpecificType Not Needed for MHD

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#61]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Regarding Open Issue mCSD_17

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The direction that the industry seems to be heading is that for FHIR based exchange, only the base URL of the FHIR server is needed. Other needed information is derived from a retrieval of the CapabilityStatement and/or by .well-known subendpoints. Therefore, I think that simply describing an endpoint as supporting a particular version of FHIR is sufficient for the needs of FHIR based ecosystems. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Do not specify a specific connection type for MHD. The hl7-fhir-rest type is sufficient. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by lukeaduncan** [comment]
Copied content to #102
