### ISSUE TITLE
Karen's Cross Not Relevant to mCSD

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#62]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Open Issue mCSD_25

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

 Karen's Cross, which deals with metadata mapping in document sharing profiles, does not seem relevant to this integration profile. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by jlamy** [comment]
I'd agree the entirety of an expanded Karen's Cross wouldn't necessarily be relevant to mCSD. But I wonder if just the subset that has to do with federation and identity/addressability would?

The advantage of a matrix like this is it would be a "one stop shop" to understand what has been profiled and where to find it. It could live in a whitepaper, appendix, or mCSD Vol 1.
