### ISSUE TITLE
Why Are Digital Certificates A Prerequisite For Asynchronous Support In mCSD

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#64]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Regarding Open Issue mCSD_28

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

It is not clear to me why support for asynchronous transactions necessitate the need of carrying certificates on the Endpoint Resource. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Define asynchronous endpoints in the mCSD Endpoint Types Code System. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by lukeaduncan** [comment]
Added to newly created open issue version of this.
