### ISSUE TITLE
Open Issue Identifier Collision

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#65]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Open and Closed Issues

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

mCSD_10, mCSD_11, and mCSD_12 seem to be used as the identifiers for multiple open issues. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Assign these issues unique identifiers

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by lukeaduncan** [comment]
Open/closed issue numbering has been fixed in the public comment version as well as creating github issues for all open issues.
