### ISSUE TITLE
Identical Value Sets On Artifacts Page

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#66]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Artifacts Summary

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

https://profiles.ihe.net/ITI/mCSD/ValueSet/MCSDEndpointTypesCoreDocShareVS and https://profiles.ihe.net/ITI/mCSD/ValueSet/MCSDEndpointTypesDocShareVS appear identical on the artifacts page

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Update titles and descriptions of these two value sets to differentiate them. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by lukeaduncan** [comment]
Fix titles in FSH files for these ValueSets.
