### ISSUE TITLE
Handling for modifierExtension and implicitRules

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#67]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Resource.implicitRules and Resource.modifierExtension require that the consumer understand their contents in order to safely process the Resource. Since we are not defining these in mCSD, should mCSD profile these to 0..0 to improve interoperability?

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

For all profiled Resources in mCSD, set the maximum cardinality of implicitRules and modifierExtension to 0. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by lukeaduncan** [comment]
Discussed on PC review call.  Will incorporate this in pull request before face to face.
